Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,7 +25,7 @@ jobs:
       run: cd
       
     - name: Clone repository
-      run: git clone https://github.com/bythebug/public_html.git
+      run: git clone https://github.com/bythebug/public_html || (echo "Git clone failed"; exit 1)
 
     - name: Deploy completed
       run: echo "Deployment completed successfully"
